theme = "papercolor-dark"

[editor]
line-number = "relative"
rulers = [80]
shell = ["zsh", "-c"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.normal]

[keys.insert]
'j' = { 'k' = "normal_mode"}
